### ISSUE TITLE
Polygon points are removed

### ISSUE THREAD

**Issue by bastrapp** [Hypercubed/angular-downloadsvg-directive#3]
After updating from 0.0.17 to 0.0.19 some polygons are not drawn properly:

This svg element:
<polygon fill="#658CAE" points="560,120 560,117 580,111 580,120" style="cursor: pointer;">
was altered in the downloaded file to this:
<polygon style="cursor: pointer; fill: rgb(101, 140, 174);">

**Comment by Hypercubed** [comment]
Thank you for reporting.  I needed to implement a whitelist of svg objects to get clean svg.  Can you please share more information of what is missing?  I can add new elements and styles.  I should also add a flag to disable or add to the list in cases like this.  PR would be great.

**Comment by bastrapp** [comment]
I am ready to create a pull request. Will you provide the appropriate .min.js version or how should I do it?

**Comment by Hypercubed** [comment]
Thanks, I'll generate the min when I test and release.

**Comment by Hypercubed** [comment]
Merged.  Thank you.
