### ISSUE TITLE
Attributes are omitted

### ISSUE THREAD

**Issue by bastrapp** [Hypercubed/angular-downloadsvg-directive#5]
SVG attributes that appear in the "styles" white list are sometimes removed. For example fill, stroke, ...

Example:
`<path class="line" d="M0,390L730,283.87755102040813" id="lines" stroke="#004078" fill="none" stroke-width="2px"></path>`
results in 
`<path class="line" d="M0,390L730,283.87755102040813" id="lines"/>`

I could write all those attributes inside the style attribute. But is there a reason that you are not supporting those SVG tags?

**Comment by Hypercubed** [comment]
I'll have to look into this.  I think I expected that if an attribute is also a style it will appear in the style tag.

**Comment by Hypercubed** [comment]
If I use your example:

```
<path class="line" d="M0,390L730,283.87755102040813" id="lines" stroke="#004078" fill="none" stroke-width="2px"></path>
```

I get:

```
<path xmlns="http://www.w3.org/2000/svg" class="line" d="M0,390L730,283.87755102040813" id="lines" style="fill: none; stroke: rgb(0, 64, 120); stroke-width: 2px;"/>
```

Attributes that are also styles are copied to the styles tag.  Since I am internally calling jquery's `.css` to get the computed styles this includes attributes that translate to styles.  If I leave the attributes it would be redundant.

Is there a good reason to keep these attributes?

**Comment by bastrapp** [comment]
With your newest version 0.0.21 it is working again. Thank you.

**Comment by Hypercubed** [comment]
Actually I introduced a bug in 0.21 that prevents the styles of children from being copied.  I'll need to fix this.  This issue is still open.

**Comment by bastrapp** [comment]
Sorry to say, but with 0.0.22 my issue is wide open again. No styles-as-attributes are exported

**Comment by Hypercubed** [comment]
In my tests whenever an attribute is also a style the style is added and the attribute is deleted.  Can you explain why this is not desired.  Is there a reason to prefer the attribute over the style?

**Comment by bastrapp** [comment]
This part of the `<defs>` section will come out in 0.0.21 as:    
```xml
<linearGradient y2="100%" x2="0" y1="0" x1="0" id="rectGradient">
    <stop stop-color="#FCFDFE" offset="0%"></stop>
    <stop stop-color="#BED5F0" offset="100%"></stop>
</linearGradient>
```
and will be stripped down in 0.0.22 to:
```xml
<linearGradient id="rectGradient" x1="0" y1="0" x2="0" y2="100%">
    <stop></stop>
    <stop></stop>
</linearGradient>
```
and a path in 0.0.21:
```xml
<path marker-end="url(#arrowhead)" d="..." stroke-linecap="butt" stroke-width="2px" stroke="#30628E" fill="none" class="link">
```
is without styles in 0.0.22:
```xml
<path class="link" d="..."></path>
```

and of a rect the stroke etc. will also be taken away:
```xml
<rect stroke="black" stroke-width="2px" style="fill: url(&quot;#rectGradient&quot;) none;" ry="2" rx="2" height="50" width="50"></rect>
```
to
```xml
<rect width="50" height="50" rx="2" ry="2" style="fill: url(#rectGradient);">
```
If you want to, I can send you a complete svg that doesn't work for me.

**Comment by Hypercubed** [comment]
Ok, I made the attr pruning lest strict.  This may lead to some noise as attributes that are also styles may appear twice but maybe still reasonable.  Please give 0.25 a try.  If it doesn't work send me an example svg.  Thanks.

**Comment by bastrapp** [comment]
0.25 ist working for me. Thanks.

**Comment by amergin** [comment]
On this matter, are there any plans to include styles originating from css classes by embedding them to the elements as in-line styles? At least [svg-crowbar](https://github.com/NYTimes/svg-crowbar) takes this approach which can be very handy when working with dynamically created figures.

**Comment by Hypercubed** [comment]
@amergin... that is exatly what this does. Is it not working for you?

**Comment by Hypercubed** [comment]
@amergin Open new issue if you are still having trouble.
